# Generated by Django 5.0.6 on 2024-06-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_path'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
